# This is a basic workflow to help you get started with Actions

name: Dev Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
            version: 1.0.5
          
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest
      - name: Interact with Terragrunt
        run: terragrunt --version
        
      - name: Plan Terragrunt
        working-directory: non-prod/eu-west-1/stage
        run: terragrunt run-all plan
        
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.5'
      - name: Install dependencies
        working-directory: .
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
